Automated feedback
ONSdigital/sdx-downstream pull request #130
Opened 2020-11-05 16:20 UTC by bkhan2

## What? and Why?
adds funcitonality to get feedback submission from sdx-store

## Checklist
  - [ X ] CHANGELOG.md updated? (if required)

2020-11-09 13:32 UTC, mfcrocker approved these changes

2020-11-10 09:19 UTC, warrenbailey submitted a review, later dismissed

2020-11-10 09:19 UTC, warrenbailey commented on app/processors/message_processor.py
> +            tx_id = id_tag.get('tx_id')
why does this need to change? 

The tx_id is passed as a parameter so not to affect existing functionality we probably should continue to use that

2020-11-10 13:13 UTC, insacuri requested changes
A few small comments.  Warrens suggested changes against all the PRs will mean this will probably change a bit soon.
Also `id_tag` isn't a great name.  Just `id` would be fine.

2020-11-10 13:13 UTC, insacuri commented on app/helpers/request_helper.py
> +    logger.info("About to get feedback from store")
The id should be added to this:
logger.info("About to get feedback from store", id=id)

2020-11-10 13:13 UTC, insacuri commented on app/helpers/request_helper.py
> +        logger.info("Successfully got feedback from store")
same comment as above with structured logging fields.

2020-11-10 13:13 UTC, insacuri commented on app/processors/message_processor.py
> +                filename = 'feedback_{}'.format(feedback_id)
Use f-strings!  They're great!
```python
filename = f'feedback_{feedback_id}'
```

2020-11-10 13:13 UTC, insacuri commented on app/settings.py
> +FTP_FEEDBACK_FOLDER = '/EDC_QFeedback'
If we're adding a new hardcoded folder, should there be another card made to add it to sdx-console?  Not vital but something to consider

2020-11-11 07:53 UTC, warrenbailey commented on app/processors/message_processor.py
> +            tx_id = id_tag.get('tx_id')
like I mentioned in the sdx-collect review, I think it may be better to add a header to message rather than modifying the message payload itself.

2020-11-16 15:05 UTC, insacuri approved these changes
Look good, there needs to be another PR around this shortly to update the scripts/reprocess.py script to accomodate the new json message format.  That can be done separately from this though (but can't get forgotten about)

2020-11-16 16:49 UTC, merged